all:
	make testtimer

testtimer:
	g++ -g -Wall -o tests/testtimer tests/testtimer.cpp ../core/src/cgenericmessagemanager.cpp ../core/src/cmessagetype.cpp src/clinuxtimer.cpp src/ctimermodule.cpp  src/ccreatetimerlistener.cpp src/cdestroytimerlistener.cpp src/ccreateperiodictimerlistener.cpp src/cdestroyperiodictimerlistener.cpp
